/* tslint:disable */
require("./Popupshow.module.css");
var styles = {
    popup: 'popup_77f6dba9',
    teams: 'teams_77f6dba9',
    welcome: 'welcome_77f6dba9',
    welcomeImage: 'welcomeImage_77f6dba9',
    father: 'father_77f6dba9',
    userdisnamebox: 'userdisnamebox_77f6dba9',
    userdisname: 'userdisname_77f6dba9',
    footer: 'footer_77f6dba9',
    footerdivcontent: 'footerdivcontent_77f6dba9',
    footercontent: 'footercontent_77f6dba9',
    footermidia: 'footermidia_77f6dba9',
    userName: 'userName_77f6dba9',
    gifimg1: 'gifimg1_77f6dba9',
    carddescription: 'carddescription_77f6dba9',
    carddescrptionparagrapfh: 'carddescrptionparagrapfh_77f6dba9',
    image: 'image_77f6dba9',
    imagecardbox: 'imagecardbox_77f6dba9',
    imagecardbox2: 'imagecardbox2_77f6dba9',
    imagecard: 'imagecard_77f6dba9',
    imagecardfooter: 'imagecardfooter_77f6dba9',
    titulo: 'titulo_77f6dba9',
    subtitulo: 'subtitulo_77f6dba9',
    description: 'description_77f6dba9',
    descrptionparagrapfh: 'descrptionparagrapfh_77f6dba9',
    videointranet: 'videointranet_77f6dba9',
    cgif: 'cgif_77f6dba9',
    modalmidiabox: 'modalmidiabox_77f6dba9',
    modalmidiabox2: 'modalmidiabox2_77f6dba9',
    modalmidia: 'modalmidia_77f6dba9',
    cgifcard: 'cgifcard_77f6dba9',
    conteudo: 'conteudo_77f6dba9',
    conteudobox: 'conteudobox_77f6dba9',
    conteudobox2: 'conteudobox2_77f6dba9',
    cgif3: 'cgif3_77f6dba9',
    cardopenmodalcgif: 'cardopenmodalcgif_77f6dba9',
    cardopenmodaltitulo: 'cardopenmodaltitulo_77f6dba9',
    cardopenmodalsubtitulo: 'cardopenmodalsubtitulo_77f6dba9',
    cardmodal: 'cardmodal_77f6dba9',
    openmodal: 'openmodal_77f6dba9',
    modalDialog: 'modalDialog_77f6dba9',
    'background-in': 'background-in_77f6dba9',
    closeModal: 'closeModal_77f6dba9',
    'background-out': 'background-out_77f6dba9',
    closeModalbackground: 'closeModalbackground_77f6dba9'
};
export default styles;
/* tslint:enable */ 
//# sourceMappingURL=Popupshow.module.scss.js.map